/* TOAST */
export const TOAST_OPEN = "TOAST_OPEN";
export const TOAST_CLOSE = "TOAST_CLOSE";

/* CONFIRM */
export const CONFIRM_OPEN = "CONFIRM_OPEN";
export const CONFIRM_CLOSE = "CONFIRM_CLOSE";

/* AUTHENTICATION */
export const AUTH = "AUTH";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE ";

/* PROGRESS */
export const PROGRESS_SHOW = "PROGRESS_SHOW";
export const PROGRESS_HIDE = "PROGRESS_HIDE";

/* LOCATION */
export const LOCATION_INIT = "LOCATION_INIT";

/* CATEGORY */
export const CATEGORY_INIT = "CATEGORY_INIT";